# Docker compose conf for the docker stack

version: '3.8'

services:
  frontend:
    image: holakarme/businessperson-frontend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - node_modules:/apps/frontend/node_modules
    ports:
      - 3000:3000
      # healthcheck:
      #  There are no curl in the alpine images
      # test: wget --no-verbose --tries=1 --spider http://127.0.0.1:3000 || exit 1
      # interval: 10s
      # timeout: 5s
      # start_period: 10s
      # retries: 2

  backend:
    image: holakarme/businessperson-backend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - static_value:/apps/backend/static
      - media_value:/apps/backend/media

      # file from the remote /home/database/sqlite/db.sqlite3 will be available in the container
      - /home/database/sqlite/db.sqlite3:/apps/backend/db.sqlite3
    ports:
      - 8000:8000
    # healthcheck:
    #   test: curl --fail http://0.0.0.0:8000 || exit 1
    #   interval: 10s
    #   timeout: 5s
    #   start_period: 10s
    #   retries: 2

  nginx:
    image: holakarme/businessperson-nginx:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    ports:
      - 80:80

    # healthcheck:
    #   test: curl --fail http://127.0.0.1:80/ || exit 1
    #   interval: 10s
    #   timeout: 5s
    #   retries: 2

    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  node_modules:
  static_value:
  media_value:
