# Docker compose conf for the docker stack

version: '3.8'

services:
  frontend:
    image: holakarme/businessperson-frontend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - node_modules:/apps/frontend/node_modules
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: holakarme/businessperson-backend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - static_value:/apps/backend/static
      - media_value:/apps/backend/media

      # file from the remote /home/database/sqlite/db.sqlite3 will be available in the container
      - /home/database/sqlite/db.sqlite3:/apps/backend/db.sqlite3
    ports:
      - 8000:8000

    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: holakarme/businessperson-nginx:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    depends_on:
      - backend:
          condition: service_healthy
      - frontend:
          condition: service_healthy

    ports:
      - 80:80

    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  node_modules:
  static_value:
  media_value:
