# Docker compose conf for the docker stack

version: '3.8'

services:
  frontend:
    image: holakarme/businessperson-frontend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - node_modules:/apps/frontend/node_modules
    ports:
      - 3000:3000

  backend:
    image: holakarme/businessperson-backend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - db:/backend/db.sqlite3
      - static_value:/apps/backend/static
      - media_value:/apps/backend/media
    ports:
      - 8000:8000

  nginx:
    image: holakarme/businessperson-nginx:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    ports:
      - 80:80

    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/

volumes:
  node_modules:
  db:
  static_value:
  media_value:
