services:

  backend:
    image: holakarme/businessperson-backend:latest
    # restart: unless-stopped
    volumes:
      - static_value:/apps/backend/static
      - media_value:/apps/backend/media

      # file from the remote /home/database/sqlite/db.sqlite3 will be available in the container
      - /home/database/sqlite/db.sqlite3:/apps/backend/db.sqlite3
    ports:
      - 8000:8000
    networks:
      - app-network

  nginx:
    image: holakarme/businessperson-nginx:latest
    depends_on:
      - backend
    # restart: unless-stopped
    ports:
      - 80:80
      - 443:443

    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - certificates:/etc/letsencrypt
      - data:/data/letsencrypt
    networks:
      - app-network

  # Перевыпкается ограниченное количество раз. Каждый деплой - перевыпуск
  certbot: 
    image: certbot/certbot
    depends_on:
      - nginx
    volumes:
      - certificates:/etc/letsencrypt
      - data:/data/letsencrypt
    command: certonly --webroot -w /data/letsencrypt --force-renewal --email peretyatko.kirill@avtorit24.ru --agree-tos --no-eff-email -d xn--24-6kcduamh0cckkold.xn--p1ai 
    networks:
      - app-network


volumes:
  node_modules:
  static_value:
  media_value:
  certificates:
  data:

networks:
  app-network:
    driver: bridge