# Docker compose conf for the docker stack

version: '3.8'

services:

  backend:
    image: holakarme/businessperson-backend:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    volumes:
      - static_value:/apps/backend/static
      - media_value:/apps/backend/media

      # file from the remote /home/database/sqlite/db.sqlite3 will be available in the container
      - /home/database/sqlite/db.sqlite3:/apps/backend/db.sqlite3
    ports:
      - 8000:8000
    networks:
      - app-network

  nginx:
    image: holakarme/businessperson-nginx:latest

    deploy:
      replicas: 1
      # restart_policy:
      #   condition: on-failure

    ports:
      - 80:80
      - 443:443

    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network

  certbot: 
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email hol peretyatko.kirill@avtorit24.ru -d xn--24-6kcduamh0cckkold.xn--p1ai --agree-tos


volumes:
  node_modules:
  static_value:
  media_value:

networks:
  app-network: