name: deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_backend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  repository: https://github.com/Avtor-IT/BP-Backend
                  ssh-key: ${{ secrets.SSH_GITHUB_BACKEND_PRIVATE_KEY  }}
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  file: ./docker/backend/Dockerfile
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/businessperson-backend:latest

    build_frontend:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  file: ./docker/frontend/Dockerfile
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/businessperson-frontend:latest

    build_nginx:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                  submodules: true
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: set up docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  file: ./docker/nginx/Dockerfile
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/businessperson-nginx:latest

    deploy:
        runs-on: ubuntu-latest
        needs:
            - build_backend
            - build_frontend
            - build_nginx
        steps:
            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: deploy to swarm
              uses: sagebind/docker-swarm-deploy-action@v2
              with:
                  remote_host: ssh://${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
                  ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
                  args: stack deploy -c ./compose.swarm.yaml businessperson --with-registry-auth
